[package]
name = "lower"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
defs = { path = "../defs" }
rustc-hash = "1"
syntax = { path = "../syntax" }
uniq = { path = "../uniq" }
