[package]
name = "statics"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
hir = { path = "../hir" }
rustc-hash = "1"
uniq = { git = "https://github.com/azdavis/language-util.git" }
