[package]
name = "parse"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
event-parse = { git = "https://github.com/azdavis/language-server-util.git" }
syntax = { path = "../syntax" }
